# Generated by Django 4.1.7 on 2023-03-11 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=10)),
                ('description', models.CharField(blank=True, default='', max_length=100)),
                ('allocated_budget', models.IntegerField()),
                ('needs_rebuilding', models.BinaryField()),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='favourite_toy',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('specifications', models.CharField(blank=True, default='', max_length=100)),
                ('endangered', models.BinaryField()),
                ('years_expected_to_live', models.IntegerField()),
                ('food_type', models.CharField(blank=True, default='', max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.area')),
            ],
        ),
        migrations.AlterField(
            model_name='animal',
            name='specie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.specie'),
        ),
    ]
