# Generated by Django 4.1.7 on 2023-03-13 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_area_animal_favourite_toy_specie_alter_animal_specie'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='content',
            field=models.TextField(default='default_value'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='specie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='animals.specie'),
        ),
    ]
