# Generated by Django 4.1.7 on 2023-03-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_job_alter_animal_options_employee_assignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={},
        ),
    ]
