# Generated by Django 4.1.7 on 2023-03-19 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_alter_assignment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='content',
            field=models.TextField(default='default_value'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='animals.job'),
        ),
    ]
