# Generated by Django 4.1.7 on 2023-03-19 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_employee_content_alter_employee_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='content',
            new_name='employees',
        ),
        migrations.AlterField(
            model_name='employee',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='animals.job'),
        ),
    ]
