# Generated by Django 4.1.7 on 2023-03-19 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_rename_content_employee_employees_alter_employee_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='area_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='area', to='animals.area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='employee_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='animals.employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='area',
            field=models.TextField(default='default_value'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='employee',
            field=models.TextField(default='default_value'),
        ),
    ]
