# Generated by Django 4.1.7 on 2023-03-19 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0008_assignment_area_id_assignment_employee_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='area',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='employee',
        ),
    ]
