# Generated by Django 4.1.7 on 2023-03-19 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0009_remove_assignment_area_remove_assignment_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='area_id',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='employee_id',
            new_name='employee',
        ),
    ]
