# Generated by Django 4.1.7 on 2023-03-19 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0010_rename_area_id_assignment_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specie',
            name='species',
            field=models.TextField(default='default_value'),
        ),
        migrations.AlterField(
            model_name='specie',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species', to='animals.area'),
        ),
    ]
