# Generated by Django 4.1.7 on 2023-03-19 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0011_specie_species_alter_specie_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specie',
            name='species',
        ),
    ]
