# Generated by Django 4.1.7 on 2023-03-19 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0014_attraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.area'),
        ),
    ]
