# Generated by Django 4.1.7 on 2023-04-01 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0016_remove_employee_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='animals.area'),
        ),
    ]
