# Generated by Django 4.2 on 2023-04-09 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0017_alter_assignment_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='animals.employee'),
        ),
    ]
