# Generated by Django 4.2 on 2023-04-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0018_alter_assignment_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='needs_rebuilding',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='specie',
            name='endangered',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
